### DISCUSSION TITLE
Unable to Save Database Dump in Docker Compose

### DISCUSSION THREAD

**Discussion by WooMai** [dragonflydb/dragonfly#1527] [Q&A] [answered]
Hello Community,

I am facing an issue while using Dragonfly DB in Docker Compose. 
I am unable to save a database dump, and the error message I receive is: `Failed to perform snapshot Permission denied: Couldn't open file for writing (is direct I/O supported by the file system?)`

Here are some details regarding my setup:
* Use `docker exec` to get inside the container and `echo "test" > /data/test.txt` works as expected
* I have attempted to save a database dump using the `SAVE` command in `redis-cli`, but also results in the mentioned error.

Here is my docker-compose.yaml

```yaml
version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - dragonfly
    networks:
      - appnet
    environment:
      - FOO=BAR

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    command:
      - "--save_schedule=*:*"
    ulimits:
      memlock: -1
    restart: always
    networks:
      - appnet
    volumes:
      - /root/myapp/data/dragonfly:/data

networks:
  appnet:
```

I would appreciate any guidance or suggestions on how to resolve this issue. Thank you in advance for your help.

**Comment by koraykoska** [comment]
Same here. @romange @dranikpg

**Comment by romange** [comment]
this works for me
```yml
version: '3'
services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    command:
      - "--save_schedule=*:*"
    ports:
      - "6379:6379"      
    ulimits:
      memlock: -1
    restart: always
    networks:
      - appnet
    volumes:
      - /tmp:/data

networks:
  appnet:
```

The problem is probably with the host folder that you map inside. Specifically, `/root/myapp/data/dragonfly` is located on a filesystem that is probably special in some way.
