### DISCUSSION TITLE
Memory limit when running in k8s

### DISCUSSION THREAD

**Discussion by lethehoa** [dragonflydb/dragonfly#2247] [Q&A] [answered]
Currently, I install dragonflydb in k8s. Here is my manifest file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonflydb
  labels:
    app: dragonflydb
spec:
  selector:
    matchLabels:
      app: dragonflydb
  template:
    metadata:
      labels:
        app: dragonflydb
    spec:
      containers:
      - name: dragonflydb
        image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
        resources:
          limits:
            memory: 1024Mi
            cpu: 200m
          requests:
            memory: 1024Mi
            cpu: 200m
        args:
          - --maxmemory=512M
          - --cache_mode=true
        ports:
        - containerPort: 6379
```

But I have the problem below.

> I20231202 05:28:49.835762     1 init.cc:70] dragonfly running in opt mode.                                                                                                                                                               I20231202 05:28:49.836225     1 dfly_main.cc:800] Starting dragonfly df-v1.12.1-053a33d24df939d1c35f3b6f233a0c57ac185184                                                                                                                  W20231202 05:28:49.836840     1 dfly_main.cc:839] SWAP is enabled. Consider disabling it when running Dragonfly.                                                                                                                          I20231202 05:28:49.836941     1 dfly_main.cc:863] Max memory limit is: 512.00MiB                                                                                                                                                          W20231202 05:28:49.836977     1 dfly_main.cc:504] Kernel is older than 5.10, switching to epoll engine.                                                                                                                                   I20231202 05:28:49.994577     1 proactor_pool.cc:147] Running 24 io threads                                                                                                                                                               E20231202 05:28:49.994702     1 dfly_main.cc:336] There are 24 threads, so 6.00GiB are required. Exiting...

![image](https://github.com/dragonflydb/dragonfly/assets/75193335/c4e8296d-7b19-46da-829e-c8a40889b7cb)
