### DISCUSSION TITLE
Question regarding maxclients param

### DISCUSSION THREAD

**Discussion by badraxas** [dragonflydb/dragonfly#2978] [Q&A] [answered]
Hi, is this parameter compatible with memcached?

I'm trying to set this parameter to 1, but I can still open as many connections as I want:
```yaml
  memcached:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: --memcached_port=11211 --cluster_mode=emulated --maxclients=1
    ports:
      - "11211:11211"
    networks:
      - network
```
