### DISCUSSION TITLE
How to select a specific version using Docker/Docker compose?

### DISCUSSION THREAD

**Discussion by Zer0xxxx** [dragonflydb/dragonfly#3233] [Q&A] [answered]
Hello!

From the docs:
https://www.dragonflydb.io/docs/getting-started/docker-compose

```bash
# Download Official Dragonfly Docker Compose File
wget https://raw.githubusercontent.com/dragonflydb/dragonfly/main/contrib/docker/docker-compose.yml

# Launch the Dragonfly Instance
docker compose up -d
```

Where https://raw.githubusercontent.com/dragonflydb/dragonfly/main/contrib/docker/docker-compose.yml is actually:

```yaml
version: '3.8'
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:
```

My question is... What is exactly `docker.dragonflydb.io/dragonflydb/dragonfly`?

Does it imply that my Docker compose would be based on the "latest" version of Dragonfly?

I don't feel comfortable about it and didn't find anything in this documentation page to safely use a specific version of Dragonfly and update it by myself whenever I want in my releases processes. :(
