### DISCUSSION TITLE
How to handle `dragonfly_pipeline_queue_length` that hangs forever (pipeline hangs)?

### DISCUSSION THREAD

**Discussion by alessio-locatelli** [dragonflydb/dragonfly#3997] [Q&A] [answered]
## Problem

~I cannot reproduce this locally, but running a simple Redis pipeline in the cloud~ (**skip all this and read my next comment https://github.com/dragonflydb/dragonfly/discussions/3997#discussioncomment-11059569**).

_(below is a Python code, but I think it is irrelevant here as the problem is related only to the DragonflyDB internal pipeline execution)_

```py
    pipe = redis_client.pipeline()
    key_count = 65536
    for i in count():
        if i == key_count:
            break
    pipe.hset(hash_name, mapping={str(i): str(j) for j in range(10_000)})
    pipe.execute()
```

results in 

![2024-10-25_17-37](https://github.com/user-attachments/assets/bc874aa2-0d13-4b33-a144-96ee32431953)

where `dragonfly_pipeline_queue_length` stays forever and no data is written.

Later in the log I have

```
Some commands are still being dispatched but didn't conclude in time. Proceeding in shutdown.
```

## Versions

```yaml
        env:
        - name: DFLY_cache_mode
          value: "false"
        - name: DFLY_enable_heartbeat_eviction
          value: "false"
        - name: DFLY_dbnum
          value: "1"
        - name: DFLY_proactor_threads
          value: "2"
        - name: DFLY_dbfilename
          value: dump
        - name: DFLY_maxmemory
          value: "5100273664"
        - name: DFLY_logtostdout
          value: "true"
        - name: DFLY_aclfile
          value: /dragonfly/snapshots/acl.file
        - name: HEALTHCHECK_PORT
          value: "9999"
        image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.24.0
```

```
    autopilot.gke.io/resource-adjustment: {"input":{"containers":[{"requests":{"cpu":"1","memory":"5Gi"},"name":"dragonfly"}]},"output":{"containers":[{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"5Gi"},"requests":{"cpu":"1","ephemeral-storage":"1Gi","memory":"5Gi"},"name":"dragonfly"}]},"modified":true}
    autopilot.gke.io/warden-version: 3.0.39
```

## Question

What to do if a pipeline hangs forever inside DragonflyDB after I call `pipe.execute()`?

#### Update:

A smaller pipeline worked. Now I have an assumption that for a too large pipeline DragonflyDB hangs forever silently. How can it abort the pipeline and raise an error to the client? 

## Related

I tried to search for "pipeline", "dragonfly_pipeline_queue_length", "Some commands are still being dispatched", but I found no related open issues or discussions.   
Additionally, `dragonfly_pipeline_queue_length` is undocumented (or I was unable to find that) and the meaning of this metric is not obvious.
