### DISCUSSION TITLE
Sidekiq no picking up jobs

### DISCUSSION THREAD

**Discussion by antarr** [dragonflydb/dragonfly#4515] [Q&A]
I'm trying to switch from redis to dragon fly on Ruby on Rails application. I'm deploying using Kamal 2. Dragon fly starts fine and I'm apple to push jobs to the queue, but not jobs are ever picked up by the workers,

```yaml
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    # cmd: "dragonfly --bind localhost --port 6379 --shard_round_robin_prefix=sidekiq"
    roles:
      - web
    port: "6379:6379"
    options:
      restart: always
      memory: 2G
    volumes:
      - /data/dragonfly:/data/dragonfly
```

**Comment by adiholden** [comment]
you can use 
  command: [
    "--port", "6379",
    "--bind", "localhost",
    "--shard_round_robin_prefix", "sidekiq",
  ]

also can you connect to dragonfly with redis cli and run `info all` this will give us more information.

**Reply by antarr** [reply]
kamal does not have a command: parameter. I tried this but can't connect after starting
```
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    cmd: "dragonfly --port 6379 --bind localhost --shard_round_robin_prefix sidekiq"
    roles:
      - web
    port: "6379:6379"
    options:
      restart: always
      memory: 2G
    volumes:
      - /data/dragonfly:/data/dragonfly
 ```
