### DISCUSSION TITLE
How to save data automatically with docker-compose?

### DISCUSSION THREAD

**Discussion by yingshaoxo** [dragonflydb/dragonfly#630] [Q&A]
In the original redis, it can save data automatically, but with dragonfly, as I tested out, it's not working.

Here is my config:

```yaml
  dragonfly: # the new redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v0.12.0
    command:
      - "--save_schedule=`*:01`" # save for every 1 minutes
      - "--dbfilename=dump.rdb"
    ports:
      - '6379:6379'
    volumes:
      - "./configs/redis_data:/data"
    restart: unless-stopped
```

Nothing appears in `./configs/redis_data/`

**Comment by romange** [comment]
`*:01` it's not every 1 minute. `*:*` is every one minute - we parse it as a glob.

**Reply by yingshaoxo** [reply]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/17190829/210202561-03d2628b-8541-4489-bcdd-13994dd0073b.png">

No, it's not working.

It says: 
```
Invalid snapshot time specifier `*:*`
```

**Comment by romange** [comment]
Weird, it worked for me via docker.

**Reply by yingshaoxo** [reply]
OK

Now I found the problems:

1. I shouldn't use '`' in the command
2. `--dbfilename` must be an absolute path under `/data` folder

> I hope one of you guys should do an update in the readme, because it didn't cover this information 
___

```yaml
  dragonfly: # the new redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v0.12.0
    command:
      - "--save_schedule=*:*" # save for every 1 minutes
      - "--dbfilename=/data/dump.rdb"
    ports:
      - '6379:6379'
    volumes:
      - "./configs/redis_data:/data"
    restart: unless-stopped
```
