### ISSUE TITLE
Helm fails when enabling prometheus rules.

### ISSUE THREAD

**Issue by Jean-Daniel** [dragonflydb/dragonfly#1015]
When enabling prometheus rules in dragonfly chart, helm fails with the following error:

```
helm process exit with code 1: Error: YAML parse error on dragonfly/templates/prometheusrule.yaml: error converting YAML to JSON: yaml: line 17: could not find expected ':'
```

This is due to the wrong indentation level used for the spec.

https://github.com/dragonflydb/dragonfly/blob/c271e131762775a53c92bbab2633c792c33bb65f/contrib/charts/dragonfly/templates/prometheusrule.yaml#L9-L14

It should be 

```yaml
    rules:
      {{- toYaml .Values.prometheusRule.spec | nindent 6 }}
```

**Comment by Pothulapati** [comment]
Hey @Jean-Daniel, Thanks for raising the issue.

I tried rendering with the following configuration:
```
serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true
  spec:
  - alert: PrometheusAlertmanagerConfigNotSynced
    expr: count(count_values("config_hash", alertmanager_config_hash)) > 1
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Prometheus AlertManager config not synced (instance {{ $labels.instance }})
      description: "Configurations of AlertManager cluster instances are out of sync\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

and got the following output:

```
# Source: dragonfly/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-dragonfly-metrics
  namespace: default
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
  - name: dragonfly
    rules:
    - alert: PrometheusAlertmanagerConfigNotSynced
      annotations:
        description: |-
          Configurations of AlertManager cluster instances are out of sync
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
        summary: Prometheus AlertManager config not synced (instance {{ $labels.instance
          }})
      expr: count(count_values("config_hash", alertmanager_config_hash)) > 1
      for: 0m
      labels:
        severity: warning
```

and the installation of the rendered worked as expected without any changes or errors. Can you expand on the input values that was submitted? 🤔 
```
