### ISSUE TITLE
SAVE of large database stalls

### ISSUE THREAD

**Issue by heikomat** [dragonflydb/dragonfly#1076]
**Describe the bug**
Calling `SAVE` never finishes when a certain set of data is currently loaded.
The dump grows for a while and then stops. Two cores stay at 100% load forever

**To Reproduce**
1. Download the [dump.rdb.zst](https://s3-de-central.profitbricks.com/factrobackups/dump.rdb.zst?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=00ccdd7103df47481e2b%2F20230412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230412T065751Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=7d1d2d43d319d3b73c82089506d930e52eaaab55e87755d991ce2ca80d492cd4) and decompress it (link is valid until 2023-04-19) (3.7GB compressed, 20GB uncompressed)
2. configure dragonfly to load from `dump.rdb`
3. Place the `dump.rdb` where dragonfly will load it
4. Start dragonfly
5. Wait for it to finish loading the dump
6. Call `SAVE`
7. Observe that dragonfly stalls after a while

**Expected behavior**
The dump should be created correctly and dragonfly should become responsive again

**Environment:**
 - OS: Ubuntu 22.04.2
 - Kernel: `Linux lindwurm 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized: Docker Compose
 - Dragonfly Version: 1.1.2
 - relevant part of `docker-compose.yml`:
    ```yml
    cloud_dragonfly:
      image: 'docker.dragonflydb.io/dragonflydb/dragonfly:1.1.2'
      restart: always
      command: 'dragonfly --logtostderr --cache_mode=false -dbnum 3 --port 6379 --maxmemory=56gb --df_snapshot_format=false --dbfilename=dump.rdb --v=1'
      ulimits:
        memlock: -1
      network_mode: "host"
      volumes:
        - cloud_dragonflydata:/data
    ```

**Reproducible Code Snippet**
```
SAVE
```

**Additional context**
The dump contains very large Hashes, two of wich have > 30.000.000 entries:
- `BusinessRuleCache_mandant_406ddbca-59ab-476c-bfb9-48fcb2fefed9` has 35.876.156 entries
- `BusinessRuleCache_mandant_09a07d10-f829-4a95-8ea0-5d8b57e962a5` has 30.490.310 entries

We're trying to migrate from KeyDB to DragonflyDB. To do so, we replicate the KeyDB to Dragonfly (which works fine).
After replication, we'd like to `SAVE` the current state to a dump periodically. This doesn't work.
It seems that the only relevant factor is the data that is currently loaded. We tried a couple of things that didn't help:
- waiting overnight (> 12 hours)
- using the `alpha` version
- disabling compression
- using the DFS-format instead of the RDB-Format
- using only one core
