### ISSUE TITLE
Seek for help on benchmarking of Dragonfly and KeyDB in Kubernetes

### ISSUE THREAD

**Issue by drinkbeer** [dragonflydb/dragonfly#113]
Hey, Dragonfly maintainers,

Thank you for your great work on this fantastic project. My teammates and I are impressed by the benchmark results and are trying to reproduce the benchmarking in Kubernetes (the reason we want to benchmark it in Kubernetes is we use k8s in our production environment).

I followed the set up in the [readme](https://github.com/dragonflydb/dragonfly#with-docker) and [dashtable](https://github.com/dragonflydb/dragonfly/blob/main/doc/dashtable.md#benchmarks) doc. **I found my benchmarking result is not as good as you guys did, so I would like to publish my benchmarking results here, and hear the suggestions from all of you on how to improve the performance.**

Any feedback are greatly appreciated. Thank you!

# Test Environment Setup

Node: 
* [n2-highmem-16](https://cloud.google.com/compute/docs/general-purpose-machines#n2-high-mem) (16 vCPU, 128GB memory)
* Kubernetes version: `v1.22.9-gke.1500`
* OS: Container-Optimized OS from Google ( Kernel Version: `5.10.109+`)

Dragonfly pod:
* Image: `docker.dragonflydb.io/dragonflydb/dragonfly`
* CPU: 8 vCPU
* Memory: 16 GB

Dragonfly info:
```
# Server
redis_version:df-0.1
redis_mode:standalone
arch_bits:64
multiplexing_api:iouring
tcp_port:6379
uptime_in_seconds:301378
uptime_in_days:3

# Clients
connected_clients:1
client_read_buf_capacity:256
blocked_clients:0
```

Dragonfly yaml file:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: dragonfly
    type: test
  name: dragonfly
  namespace: jason-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
      name: dragonfly
  serviceName: dragonfly
  template:
    metadata:
      annotations:
        ad.datadoghq.com/redis.check_names: '["redisdb"]'
        ad.datadoghq.com/redis.init_configs: '[{}]'
      labels:
        app: dragonfly
        name: dragonfly
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        command: ["/bin/sh"]
        args: ["-c", "ulimit -l unlimited && dragonfly --logtostderr"]
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 3
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
            memory: 16000Mi
          requests:
            cpu: "8"
            memory: 16000Mi
        securityContext:
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - SETGID
            - SETFCAP
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: true
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=8192;sysctl -w net.ipv4.tcp_max_syn_backlog=8192;echo never > /host-sys/kernel/mm/transparent_hugepage/enabled;echo never > /host-sys/kernel/mm/transparent_hugepage/defrag
        image: gcr.io/shopify-docker-images/cloud/busybox:1.0
        imagePullPolicy: IfNotPresent
        name: system-init
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host-sys
          name: host-sys
      nodeSelector:
        role: vecache
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
      tolerations:
      - effect: NoExecute
        key: app
        operator: Equal
        value: vecache
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: vecache
        maxSkew: 4
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: vecache
        maxSkew: 4
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    namebuddy.shopify.io/cname: dragonfly-0.jason-test.staging-cq-state-us-east1-1.test
    namebuddy.shopify.io/dns: ttl=5
  labels:
    app: dragonfly
    type: test
  name: dragonfly-0
  namespace: jason-test
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: dragonfly-0
```

Keydb pod:
* Image: 6.0.16 (https://github.com/JohnSully/KeyDB/archive/v6.0.16.zip)
* CPU: 8 vCPU
* Memory: 16 GB

KeyDB info
```
# Server
redis_version:6.0.16
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4d5c208d4d774a11
redis_mode:standalone
os:Linux 5.10.109+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.5.0
process_id:1
run_id:8d4e6f7ffe3a90f66aa4ce8f84155d463a74d546
tcp_port:6379
uptime_in_seconds:306392
uptime_in_days:3
hz:10
configured_hz:10
lru_clock:10415189
executable:/usr/local/bin/keydb-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:1
client_recent_max_input_buffer:4
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:0
thread_0_clients:1
thread_1_clients:0
thread_2_clients:0
thread_3_clients:0
```

We are using an internal version of KeyDB. KeyDB yaml file:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vecache
    type: test
  name: vecache
  namespace: jason-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vecache
      name: vecache
  serviceName: vecache
  template:
    metadata:
      annotations:
        ad.datadoghq.com/redis.check_names: '["redisdb"]'
        ad.datadoghq.com/redis.init_configs: '[{}]'
      labels:
        app: vecache
        name: vecache
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --maxmemory 8000Mb
        - --server-threads 4
        image: gcr.io/shopify-docker-images/cloud/vecache:1.0-6.0.16
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 3
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
            memory: 16000Mi
          requests:
            cpu: "8"
            memory: 16000Mi
        securityContext:
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - SETGID
            - SETFCAP
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=8192;sysctl -w net.ipv4.tcp_max_syn_backlog=8192;echo never > /host-sys/kernel/mm/transparent_hugepage/enabled;echo never > /host-sys/kernel/mm/transparent_hugepage/defrag
        image: gcr.io/shopify-docker-images/cloud/busybox:1.0
        imagePullPolicy: IfNotPresent
        name: system-init
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host-sys
          name: host-sys
      nodeSelector:
        role: vecache
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
      tolerations:
      - effect: NoExecute
        key: app
        operator: Equal
        value: vecache
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: vecache
        maxSkew: 4
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: vecache
        maxSkew: 4
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    namebuddy.shopify.io/cname: vecache-0.jason-test.staging-cq-state-us-east1-1.test
    namebuddy.shopify.io/dns: ttl=5
  labels:
    app: vecache
    type: test
  name: vecache-0
  namespace: jason-test
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: vecache-0
```

The memtier_benchmark job for Dragonfly:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: memtier-dragonfly
  namespace: jason-test
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: memtier
    spec:
      containers:
      - name: memtier
        image: redislabs/memtier_benchmark
        args: ["-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-n 200000", "-d 300", "--pipeline=5", "--clients=10", "--threads=5", "--run-count=2", "--hide-histogram", "--key-prefix='key:'", "--key-minimum=1", "--key-maximum=10000", "--key-pattern=S:R", "--ratio=1:3"]
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
         - name: REDIS_PORT
           value: "6379"
         - name: REDIS_SERVER
           value: "dragonfly-0.jason-test.svc.cluster.local"  # can be full hostname or just the resource name in k8s
        imagePullPolicy: Always
      tolerations:
      - effect: NoExecute
        key: app
        operator: Equal
        value: vecache
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      restartPolicy: OnFailure
```

The memtier_benchmark job for keydb:
```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: memtier-vecache
  namespace: jason-test
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: memtier
    spec:
      containers:
      - name: memtier
        image: redislabs/memtier_benchmark
        args: ["-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-n 200000", "-d 300", "--pipeline=5", "--clients=10", "--threads=5", "--run-count=2", "--hide-histogram", "--key-prefix='key:'", "--key-minimum=1", "--key-maximum=10000", "--key-pattern=S:R", "--ratio=1:3"]
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
         - name: REDIS_PORT
           value: "6379"
         - name: REDIS_SERVER
           value: "vecache-0.jason-test.staging-cq-state-us-east1-1.test"  # can be full hostname or just the resource name in k8s
        imagePullPolicy: Always
      tolerations:
      - effect: NoExecute
        key: app
        operator: Equal
        value: vecache
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      restartPolicy: OnFailure

```

# Test Result

Here are the results of the tests.

I am impressed by the memory utilization of Dragonfly. Dragonfly uses only (31.19/117.3*100=) 26.59% of memory in KeyDB. Dragonfly also has better `Get` performance (higher throughput, lower latency).
But KeyDB performs better in `Set` throughput and latency. In the mixed-set-get case, KeyDB also has better throughput, and latency.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/3954499/171945552-61b8694a-a90c-4d74-a510-11fdfdb82ad3.png">

## Pure Set

        args: ["-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-n 200000", "-d 300", "--pipeline=5", "--clients=10", "--threads=5", "--run-count=2", "--hide-histogram", "--key-prefix='key:'", "--key-minimum=1", "--key-maximum=10000", "--key-pattern=S:R", "--ratio=1:0"]

VECache (KeyDB)
* Throughput: 25246.27 ops/sec, 8478.19 KB/sec
* Latency: 10.07700 ms
* used_memory_human:117.30M
```
➜  Documents k logs memtier-vecache-v5s97
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 405 secs]  0 threads:    10000000 ops,   39564 (avg:   24665) ops/sec, 12.98MB/sec (avg: 8.09MB/sec),  6.36 (avg: 10.08) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 404 secs]  0 threads:    10000000 ops,   31802 (avg:   24697) ops/sec, 10.43MB/sec (avg: 8.10MB/sec),  7.78 (avg: 10.07) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        25378.16          ---          ---     10.07100      8522.48
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      25378.16         0.00         0.00     10.07100      8522.48


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        25114.38          ---          ---     10.08300      8433.89
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      25114.38         0.00         0.00     10.08300      8433.89


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        25246.27          ---          ---     10.07700      8478.19
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      25246.27         0.00         0.00     10.07700      8478.19
```

Dragonfly
* Throughput: 19307.83 ops/sec, 6483.94 KB/sec
* Latency: 12.99300 ms
* used_memory_human:31.19MiB
```
➜  Documents k logs memtier-dragonfly-j9l8m
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 519 secs]  0 threads:     9999996 ops,   23093 (avg:   19231) ops/sec, 7.58MB/sec (avg: 6.31MB/sec), 10.80 (avg: 12.96) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 522 secs]  0 threads:    10000000 ops,   21434 (avg:   19131) ops/sec, 7.03MB/sec (avg: 6.27MB/sec), 11.61 (avg: 13.03) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        19647.63          ---          ---     12.96000      6598.05
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      19647.63         0.00         0.00     12.96000      6598.05


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        18968.02          ---          ---     13.02600      6369.83
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      18968.02         0.00         0.00     13.02600      6369.83


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        19307.83          ---          ---     12.99300      6483.94
Gets            0.00         0.00         0.00      0.00000         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals      19307.83         0.00         0.00     12.99300      6483.94
```

## Pure Get

        args: ["-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-n 200000", "-d 300", "--pipeline=5", "--clients=10", "--threads=5", "--run-count=2", "--hide-histogram", "--key-prefix='key:'", "--key-minimum=1", "--key-maximum=10000", "--key-pattern=S:R", "--ratio=0:1"]

VECache (KeyDB)
* Throughput: 25357.45 ops/sec, 8364.74 KB/sec
* Latency: 9.93550 ms
* used_memory_human:117.30M
```
➜  Documents k logs memtier-vecache-xh6xj
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 400 secs]  0 threads:    10000000 ops,   46369 (avg:   24938) ops/sec, 14.94MB/sec (avg: 8.03MB/sec),  5.37 (avg:  9.97) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 398 secs]  0 threads:     9999999 ops,   57272 (avg:   25116) ops/sec, 18.45MB/sec (avg: 8.09MB/sec),  4.36 (avg:  9.90) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets        25426.75     25426.75         0.00      9.90000      8387.60
Waits           0.00          ---          ---      0.00000          ---
Totals      25426.75     25426.75         0.00      9.90000      8387.60


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets        25288.15     25288.15         0.00      9.97100      8341.88
Waits           0.00          ---          ---      0.00000          ---
Totals      25288.15     25288.15         0.00      9.97100      8341.88


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets        25357.45     25357.45         0.00      9.93550      8364.74
Waits           0.00          ---          ---      0.00000          ---
Totals      25357.45     25357.45         0.00      9.93550      8364.74
```

Dragonfly
* Throughput: 27705.71 ops/sec, 9139.37 KB/sec
* Latency: 9.11100 ms
* used_memory_human:31.19MiB
```
➜  Documents k logs memtier-dragonfly-5kzsm
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 365 secs]  0 threads:     9999999 ops,   83523 (avg:   27366) ops/sec, 26.91MB/sec (avg: 8.82MB/sec),  2.77 (avg:  9.11) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 363 secs]  0 threads:     9999999 ops,   84975 (avg:   27502) ops/sec, 27.37MB/sec (avg: 8.86MB/sec),  2.69 (avg:  9.07) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets        27705.71     27705.71         0.00      9.11100      9139.37
Waits           0.00          ---          ---      0.00000          ---
Totals      27705.71     27705.71         0.00      9.11100      9139.37


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets            0.00         0.00         0.00      9.06700         0.00
Waits           0.00          ---          ---      0.00000          ---
Totals          0.00         0.00         0.00      9.06700         0.00


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets            0.00          ---          ---      0.00000         0.00
Gets        13852.86     13852.86         0.00      9.08900      4569.68
Waits           0.00          ---          ---      0.00000          ---
Totals      13852.86     13852.86         0.00      9.08900      4569.68
```

## Mixed Set-Get (1:3)

        args: ["-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-n 200000", "-d 300", "--pipeline=5", "--clients=10", "--threads=5", "--run-count=2", "--hide-histogram", "--key-prefix='key:'", "--key-minimum=1", "--key-maximum=10000", "--key-pattern=S:R", "--ratio=1:3"]

VECache (KeyDB):
* Throughput: 31736.69 ops/sec, 10507.80 KB/sec
* Latency: 8.16500 ms
* used_memory_human:117.30M
```
➜  Documents k logs memtier-vecache-qvgq6
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 327 secs]  0 threads:    10000000 ops,   36385 (avg:   30555) ops/sec, 11.77MB/sec (avg: 9.88MB/sec),  6.85 (avg:  8.13) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 330 secs]  0 threads:    10000000 ops,   34522 (avg:   30286) ops/sec, 11.16MB/sec (avg: 9.79MB/sec),  7.22 (avg:  8.20) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         8009.01          ---          ---      8.13400      2681.06
Gets        24027.04     24027.04         0.00      8.12800      7925.85
Waits           0.00          ---          ---      0.00000          ---
Totals      32036.06     24027.04         0.00      8.12900     10606.91


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         7859.33          ---          ---      8.20400      2630.95
Gets        23578.00     23578.00         0.00      8.20000      7777.73
Waits           0.00          ---          ---      0.00000          ---
Totals      31437.33     23578.00         0.00      8.20100     10408.68


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         7934.17          ---          ---      8.16900      2656.01
Gets        23802.52     23802.52         0.00      8.16400      7851.79
Waits           0.00          ---          ---      0.00000          ---
Totals      31736.69     23802.52         0.00      8.16500     10507.80
```

Dragonfly:
* Throughput: 23444.44 ops/sec, 7762.29 KB/sec
* Latency: 10.65200 ms
* used_memory_human:31.19MiB
```
➜  Documents k logs memtier-dragonfly-ws9rr
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 425 secs]  0 threads:    10000000 ops,   25440 (avg:   23479) ops/sec, 8.23MB/sec (avg: 7.59MB/sec), 10.22 (avg: 10.60) msec latency

[RUN #2] Preparing benchmark client...
[RUN #2] Launching threads now...
[RUN #2 100%, 430 secs]  0 threads:    10000000 ops,   31976 (avg:   23230) ops/sec, 10.34MB/sec (avg: 7.51MB/sec),  7.79 (avg: 10.71) msec latency

5         Threads
10        Connections per thread
200000    Requests per client


BEST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         5922.85          ---          ---     10.61200      1982.71
Gets        17768.56     17768.56         0.00     10.59100      5861.35
Waits           0.00          ---          ---      0.00000          ---
Totals      23691.41     17768.56         0.00     10.59600      7844.06


WORST RUN RESULTS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         5799.37          ---          ---     10.71700      1941.37
Gets        17398.11     17398.11         0.00     10.70500      5739.15
Waits           0.00          ---          ---      0.00000          ---
Totals      23197.48     17398.11         0.00     10.70800      7680.52


AGGREGATED AVERAGE RESULTS (2 runs)
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets         5861.11          ---          ---     10.66450      1962.04
Gets        17583.33     17583.33         0.00     10.64800      5800.25
Waits           0.00          ---          ---      0.00000          ---
Totals      23444.44     17583.33         0.00     10.65200      7762.29
```
