### ISSUE TITLE
maxmemory not set automatically based on CPU request requirements

### ISSUE THREAD

**Issue by roehnan** [dragonflydb/dragonfly#1491]
**Describe the bug**
When running on Kubernetes, the maxmemory that Dragonfly DB decides that it needs for itself is not sufficient for the amount of CPU resources requested and it refuses to start unless `--maxmemory` is specified manually.

Dragonfly DB knows that more memory is available and it also knows how much memory is required to support the CPU requests, but chooses a smaller amount and fails to load. 

Here is the log of the failure to run:

```
I20230628 17:25:42.325246     1 init.cc:69] dragonfly running in opt mode.
I20230628 17:25:42.325362     1 dfly_main.cc:618] Starting dragonfly df-v1.4.0-6d4d740d6e2a060cbbbecd987ee438cc6e60de79
I20230628 17:25:42.325569     1 dfly_main.cc:658] maxmemory has not been specified. Deciding myself....
I20230628 17:25:42.325585     1 dfly_main.cc:662] Found 19.00GiB available memory. Setting maxmemory to 15.20GiB
I20230628 17:25:42.372169    26 uring_proactor.cc:158] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20230628 17:25:42.524402     1 proactor_pool.cc:147] Running 72 io threads
E20230628 17:25:42.524503     1 dfly_main.cc:305] There are 72 threads, so 18.00GiB are required. Exiting...
```

**To Reproduce**
1. Deploy to Kubernetes with helm, supplying appropriate resource requests. Do **not** include `--maxmemory` in `extraArgs`.
2. See error

**Expected behavior**
`maxmemory` (when not supplied as a command-line arg) should be determined based on available resources **and** CPU/thread requirements.

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Kernel: 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 GNU/Linux
 - Containerized?: Kubernetes
 - Dragonfly Version: 1.4.0

**Reproducible Code Snippet**
Dragonfly DB installed via helm:
```
helm upgrade -f myvals.yaml -n jbiagio --install dragonfly-messagechannels oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly --version v1.4.0
```

Contents of `myvals.yaml`:
```
extraArgs:
  - "--cluster_mode=emulated"
  - "--maxmemory=18gb"
  - "--dbnum=1"
  - "--cache_mode=true"
  - "--version_check=false"

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

podAnnotations:
  prometheus.io/port: "6379"
  prometheus.io/scrape: "true"

resources:
  requests:
    cpu: "8"
    memory: 18Gi
  # -- The resource limits for the containers
  limits:
    memory: 19Gi
```
