### ISSUE TITLE
Installation via Helm fails on GKE Autopilot

### ISSUE THREAD

**Issue by dbt-lucka** [dragonflydb/dragonfly#1516]
Cannot install simple dragonfly helm chart (without configuration) on GKE Autopilot.

```
Helm install failed: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-default-linux-capabilities]":["linux capability 'SYS_ADMIN' on container 'dfdaemon' not allowed; Autopilot only allows the capabilities: 'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT,SYS_PTRACE'."],"[denied by autogke-disallow-privilege]":["container mount-netns is privileged; not allowed in Autopilot"],"[denied by autogke-no-write-mode-hostpath]":["hostPath volume run in container dfdaemon is accessed in write mode; disallowed in Autopilot.","hostPath volume hostns in container mount-netns is accessed in write mode; disallowed in Autopilot.","hostPath volume run in container mount-netns is accessed in write mode; disallowed in Autopilot."]}
Requested by user: 'system:serviceaccount:flux-system:helm-controller', groups: 'system:serviceaccounts,system:serviceaccounts:flux-system,system:authenticated'.
```

formatted: 
```
{
  "[denied by autogke-default-linux-capabilities]": [
    "linux capability 'SYS_ADMIN' on container 'dfdaemon' not allowed; Autopilot only allows the capabilities: 'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT,SYS_PTRACE'."
  ],
  "[denied by autogke-disallow-privilege]": [
    "container mount-netns is privileged; not allowed in Autopilot"
  ],
  "[denied by autogke-no-write-mode-hostpath]": [
    "hostPath volume run in container dfdaemon is accessed in write mode; disallowed in Autopilot.",
    "hostPath volume hostns in container mount-netns is accessed in write mode; disallowed in Autopilot.",
    "hostPath volume run in container mount-netns is accessed in write mode; disallowed in Autopilot."
  ]
}
```

Any ideas? It seems that Dragonfly needs access to some kernel settings that GCP disallows in autopilot mode.

GKE Autopilot Cluster on GCP running version 1.25.9-gke.2300

Helm Chart installed via FluxCD: 

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dragonfly
  name: dragonfly
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 10m
  url: https://dragonflyoss.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  interval: 5m
  chart:
    spec:
      chart: dragonfly
      version: '1.0.3'
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  values:
    
    image:
      tag: 1.4.0
```
