### ISSUE TITLE
Dragonfly DB exits with error code 132

### ISSUE THREAD

**Issue by sargon64** [dragonflydb/dragonfly#1642]
To reproduce, run a docker compose instance with the following compose.yml file:
```
version: '3.8'
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:
```

**Environment:**
 - OS: ubuntu `22.04`
 - Kernel: `5.15.0-78-generic`
 - Containerized: `Docker Compose`
 - Dragonfly Version: `1.7.1`
