### ISSUE TITLE
Dragonfly Unexpectedly Closes Client Connections

### ISSUE THREAD

**Issue by nickamorim** [dragonflydb/dragonfly#1763]
**Describe the bug**

When running a simple benchmark on Dragonfly via [memtier_benchmark](https://github.com/RedisLabs/memtier_benchmark) on Kubernetes, Dragonfly closes the client connection when the payload size is >225 bytes. I'm using the Memcached ASCII protocol.

Here are some relevant Dragonfly logs (`--v=5`):
```
I20230829 13:27:20.693219     9 listener_interface.cc:119] sock[14] Accepted 242.9.130.223:52876
I20230829 13:27:20.693253     9 dragonfly_listener.cc:288] CPU/NAPI for connection 14 is 6/0
I20230829 13:27:20.693289     9 epoll_proactor.cc:276] PRO[0] Fetched 1 cqes
I20230829 13:27:20.693297     9 listener_interface.cc:194] sock[14] Running connection
I20230829 13:27:20.693302     9 dragonfly_listener.cc:229] Opening connection 1
I20230829 13:27:20.693331     9 epoll_proactor.cc:276] PRO[0] Fetched 1 cqes
I20230829 13:27:20.693349     9 epoll_socket.cc:363] sock[14] Error system:103 on 242.9.130.223:52876
I20230829 13:27:20.693361     9 dragonfly_connection.cc:481] Before dispatch_fb.join()
I20230829 13:27:20.693368     9 dragonfly_connection.cc:483] After dispatch_fb.join()
I20230829 13:27:20.693375     9 dragonfly_connection.cc:354] Closed connection for peer 242.9.130.223:52876
I20230829 13:27:20.693382     9 listener_interface.cc:203] sock[14] After HandleRequests
I20230829 13:27:20.693387     9 dragonfly_listener.cc:256] Closing connection 1
```

**To Reproduce**
1. Apply the following Dragonfly Deployment (note that this issue persists without setting `proactor_threads` and/or `maxmemory`):
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dragonfly
  name: dragonfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          args:
            - --proactor_threads=4
            - --maxmemory=4gb
            - --memcached_port=11212
            - --logtostderr
            - --v=5
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 5Gi
              cpu: 4
          ports:
            - containerPort: 11212
          securityContext:
            privileged: true
            runAsNonRoot: false
```
2. Apply a `memtier_benchmark` Deployment
```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: memtier-dragonfly
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: memtier
    spec:
      containers:
        - name: memtier
          image: redislabs/memtier_benchmark
          args:
            [
              "--server=242.9.130.222",
              "--port=11212",
              "--protocol=memcache_text",
              "--requests=10",
              "--data-size=225",
              "--clients=1",
              "--threads=1",
              "--run-count=1",
              "--hide-histogram",
              "--distinct-client-seed",
            ]
          resources:
            limits:
              cpu: 1
              memory: 256Mi
            requests:
              cpu: 512m
              memory: 128Mi
      restartPolicy: OnFailure
```
3. Tail the logs of the benchmark and Dragonfly container

**Expected behavior**

The benchmark job should run to completion without any `Connection reset by peer` errors.

**Environment (please complete the following information):**
 - OS:
 ```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=b15e582c1dbbf0e6f06747082754e5c5a71ea426
GOOGLE_CRASH_ID=Lakitu
VERSION=101
VERSION_ID=101
BUILD_ID=17162.210.48
```
 - Kernel: `Linux dragonfly-67f948ffc8-2p6bj 5.15.107+ #1 SMP Thu Jun 29 09:19:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized?: Kubernetes
 - Dragonfly Version:
 ```
root@dragonfly-67f948ffc8-2p6bj:/data# dragonfly --version
dragonfly v1.8.0-7c99d2d1111e2636556ad8c2afad43c396906d01
build time: 2023-08-08 19:58:04
```
