### ISSUE TITLE
Unable to use dragonfly with TLS configuration

### ISSUE THREAD

**Issue by avramenkovladyslav** [dragonflydb/dragonfly#2146]
**Describe the bug**
When I'm providing configuration in helm with TLS like this:

```
podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

serviceMonitor:
  enabled: true
passwordFromSecret:
  enable: true
  existingSecret:
    name: "dragonfly"
    key: "DRAGONFLY_PASSWORD"
tls:
  enabled: true
  existing_secret: ""
  cert: |
    -----BEGIN CERTIFICATE-----
****CERTIFICATIE_BODY****
    -----END CERTIFICATE-----

  key: |
    -----BEGIN RSA PRIVATE KEY-----
****KEY_BODY****
    -----END RSA PRIVATE KEY-----
```

and using TLS connection with our .NET applications then dragonfly fails with error:

`8 dragonfly_connection.cc:385] Error handshaking error:1408F10B:SSL routines:ssl3_get_record:wrong version number`
`F20231108 11:54:04.705008    10 tls_engine.cc:128] Unexpected error error:00000000:lib(0):func(0):reason(0) 0 when consuming 141 bytes from BIO, BIO_C_NREAD0 returns -1`
[Full logs output](https://gist.github.com/avramenkovladyslav/a295918889471169feb5f0d577094d87)

Meanwhile, connection on RedisInsight with TLS working well

**Environment:**
 - Containerized: AWS EKS, Helm CLI
 - Dragonfly Version: [1.12.1]
