### ISSUE TITLE
Dragonfly panics on start with Docker

### ISSUE THREAD

**Issue by AlphaNecron** [dragonflydb/dragonfly#2391]
**Describe the bug**
Dragonfly crashes on start with minimal configuration.

```
I20240109 06:27:39.990960     1 init.cc:70] dragonfly running in opt mode.
I20240109 06:27:39.991027     1 dfly_main.cc:800] Starting dragonfly df-v1.13.0-f39eac5bcaf7c8ffe5c433a0e8e15747391199d9
* Logs will be written to the first available of the following paths:
/tmp/dragonfly.*
./dragonfly.*
* For the available flags type dragonfly [--help | --helpfull]
* Documentation can be found at: https://www.dragonflydb.io/docs
F20240109 06:27:39.991153     1 dfly_main.cc:659] Check failed: res.size() == 2u (1 vs. 2)
*** Check failure stack trace: ***
    @     0x55b52bccb9f3  google::LogMessage::SendToLog()
    @     0x55b52bcc41b7  google::LogMessage::Flush()
    @     0x55b52bcc5b3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b52b31250d  _ZZN4dfly12_GLOBAL__N_137UpdateResourceLimitsIfInsideContainerEPN2io11MemInfoDataEPmENKUlSt17basic_string_viewIcSt11char_traitsIcEES4_E0_clES8_S4_.isra.0
    @     0x55b52b2ee685  main
    @     0x7f159c90a083  __libc_start_main
    @     0x55b52b31080e  _start
    @              (nil)  (unknown)
*** SIGABRT received at time=1704781659 on cpu 4 ***
PC: @     0x7f159c92900b  (unknown)  raise
[failure_signal_handler.cc : 345] RAW: Signal 11 raised at PC=0x7f159c908941 while already in AbslFailureSignalHandler()
*** SIGSEGV received at time=1704781659 on cpu 4 ***
PC: @     0x7f159c908941  (unknown)  abort
```

**To Reproduce**
1. Install Docker Compose
2. Clone example `docker-compose.yml`.
3. Do `docker compose up -d` 

**Expected behavior**
It should be working properly.

**Environment (please complete the following information):**
 - OS: `Debian 12 (Bookworm)`
 - Kernel: `6.6.10-1-liquorix-amd64`
 - Containerized?: Docker Compose
 - Dragonfly Version: 1.13.0

**Reproducible Code Snippet**
```yml
version: '3'
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    cpuset: '0-5'
    mem_reservation: '1G'
    mem_limit: '2G'
    restart: unless-stopped
    ulimits:
      memlock: -1
    network_mode: host
#    ports:
#      - 6379:6379
    command:
      - '--conn_io_threads=8'
      - '--use_zset_tree=true'
      - '--maxmemory=1536MB'
      - '--cache_mode=true'
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:
```
This is my altered `docker-compose.yml`, Dragonfly still refuses to start with default `docker-compose.yml`.
