### ISSUE TITLE
CPU 100% iowait

### ISSUE THREAD

**Issue by BlackYuzia** [dragonflydb/dragonfly#2444]
**Describe the bug**

When I run dragonfly docker container I get 100% CPU load (**iowait**)
![image](https://github.com/dragonflydb/dragonfly/assets/25010528/88c8be11-32e1-4682-92ec-2ad423d5c83f)

If I disable container, then I get all normal
![image](https://github.com/dragonflydb/dragonfly/assets/25010528/75efa442-3944-4227-aa44-97d6110b138d)

**To Reproduce**
1. Run docker container with `dragonfly:latest` image
2. Open htop and enable `Detailed CPU Time`
![image](https://github.com/dragonflydb/dragonfly/assets/25010528/9be9b7bf-922c-4109-a12e-9770c0c455c4)
3. Profit

**Expected behavior**
Didn't consume all CPU Time for **iowait**

**Screenshots**

**Environment (please complete the following information):**
 - OS: **Ubuntu 22.04**
 - Kernel: `5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized: **Docker**
 - Dragonfly Version: **latest** (idk what exactly, image hash `sha256:ac30f1740e1aaeb8edd697b823a1ca747ee05282b872fffb769fabfdafb0d40a`)

**Additional context**

I have installed swap with zram.
`vm.swappines=60`

```yaml
version: "3.9"

services:
  dragonfly:

    hostname: "dragonfly"
    image: "docker.dragonflydb.io/dragonflydb/dragonfly:latest"
    ulimits:
      memlock: -1
    volumes:
      - "dragonfly-data:/data"
    restart: always
    networks:
      - dragonfly-vnet

volumes:
  dragonfly-data:

networks:
  dragonfly-vnet:
    external: true

```

Maybe I miss something, feel free to ask if you need something else too.
