### ISSUE TITLE
DFLY_PASSWORD environment variable was deprecated in favor of DFLY_requirepass

### ISSUE THREAD

**Issue by mprimeaux** [dragonflydb/dragonfly#2482]
**Describe the bug**

* Minikube 1.32.0
* Kubernetes v1.28.3

Version `1.14.1` of the Helm chart fails with an exception when defining the `passwordFromSecret` stanza with `enabled: true`. Here the stanza:

```yaml
# If enabled will set DFLY_PASSOWRD environment variable with the specified existing secret value
# Note that if enabled and the secret does not exist pods will not start
passwordFromSecret:
  enable: true
  existingSecret:
    name: "cache-redis-cluster"
    key: "redis-password"
```

The exception is:

```go
I20240125 22:42:52.437618     1 init.cc:70] dragonfly running in opt mode.
F20240125 22:42:52.437695     1 dfly_main.cc:557] DFLY_PASSWORD environment variable was deprecated in favor of DFLY_requirepass
*** Check failure stack trace: ***
    @     0xaaaab5a110b4  google::LogMessage::SendToLog()
    @     0xaaaab5a0a198  google::LogMessage::Flush()
    @     0xaaaab5a0bad4  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab5192870  ParseFlagsFromEnv()
    @     0xaaaab516f650  main
    @     0xffffae015e10  __libc_start_main
    @     0xaaaab5190f70  (unknown)
*** SIGABRT received at time=1706222572 on cpu 4 ***
PC: @     0xffffae028d78  (unknown)  raise
    @     0xaaaab5a64bec        480  absl::lts_20230802::AbslFailureSignalHandler()
    @     0xffffae2b27cc  1165424976  (unknown)
    @     0xffffae015aac        304  abort
    @     0xaaaab5a16974        336  google::DumpStackTraceAndExit()
    @     0xaaaab5a0a794        192  google::LogMessage::Fail()
    @     0xaaaab5a110b4         16  google::LogMessage::SendToLog()
    @     0xaaaab5a0a198        208  google::LogMessage::Flush()
    @     0xaaaab5a0bad4         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab5192870         16  ParseFlagsFromEnv()
    @     0xaaaab516f650        512  main
    @     0xffffae015e10       2272  __libc_start_main
[failure_signal_handler.cc : 345] RAW: Signal 5 raised at PC=0xffffae015b7c while already in AbslFailureSignalHandler()
*** SIGTRAP received at time=1706222572 on cpu 4 ***
PC: @     0xffffae015b7c  (unknown)  abort
    @     0xaaaab5a64bec        480  absl::lts_20230802::AbslFailureSignalHandler()
    @     0xffffae2b27cc  1165425280  (unknown)
    @     0xaaaab5a16974        336  google::DumpStackTraceAndExit()
    @     0xaaaab5a0a794        192  google::LogMessage::Fail()
    @     0xaaaab5a110b4         16  google::LogMessage::SendToLog()
    @     0xaaaab5a0a198        208  google::LogMessage::Flush()
    @     0xaaaab5a0bad4         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab5192870         16  ParseFlagsFromEnv()
    @     0xaaaab516f650        512  main
    @     0xffffae015e10       2272  __libc_start_main
Stream closed EOF for go-scriptures/dragonfly-66d79dbdbd-l82x9 (dragonfly)

```

**To Reproduce**
1.  With version `1.14.1` of the Helm chart, set the stanza as per above.
2. Create the secret with the related password and key.
3. Deploy the chart.

**Expected behavior**
I expect Dragonfly to be deployed with the specified password as defined in the existing secret.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: [Bare Metal, Docker, Docker Compose, Docker Swarm, Kubernetes, Other]
 - Dragonfly Version: [e.g. 0.3.0]

**Reproducible Code Snippet**

```yaml
# If enabled will set DFLY_PASSOWRD environment variable with the specified existing secret value
# Note that if enabled and the secret does not exist pods will not start
passwordFromSecret:
  enable: true
  existingSecret:
    name: "cache-redis-cluster"
    key: "redis-password"
```

**Additional context**

I suspect the chart needs to set the correct environment variable given the exception message: `DFLY_PASSWORD environment variable was deprecated in favor of DFLY_requirepass`

**Comment by mprimeaux** [comment]
I assume [this stanza](https://github.com/dragonflydb/dragonfly/blob/a5b9401449599ad8c5b99327452f0f5655b0121d/contrib/charts/dragonfly/templates/_pod.tpl#L94) needs to be updated to conditionally set the correct environment variable depending on the version of the container image.

**Comment by romange** [comment]
@mprimeaux would you like to send a fix? @Pothulapati  to follow up

**Comment by mprimeaux** [comment]
> @mprimeaux would you like to send a fix? @Pothulapati to follow up

Sure. I’ll work on that first thing tomorrow.

**Comment by Pothulapati** [comment]
(Assigned myself so that I can follow this up with review)

**Comment by romange** [comment]
@mprimeaux  ping. would you like that we fix it ourselves?

**Comment by mprimeaux** [comment]
Thanks for the ping. My sincere apologies for the delay as I had a few time-sensitive tasks at work that took priority. I will submit a PR by tomorrow morning US-time.

**Comment by mprimeaux** [comment]
I ran `go test -v ./... -update` to ensure the golden files were updated for CI.

**Comment by mprimeaux** [comment]
Thanks for merging the PR. I need to dig into this a bit but the new chart (v1.4.2) still results in the deployment object using `DFLY_PASSWORD` in the stanza. 

Here's the resulting dry run:

```yaml
---
# Source: dragonfly/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dragonfly
  namespace: go-scriptures
  labels:
    helm.sh/chart: dragonfly-v1.14.2
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/version: "v1.14.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: dragonfly/templates/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-metrics
  namespace: go-scriptures
  labels:
    helm.sh/chart: dragonfly-v1.14.2
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/version: "v1.14.2"
    app.kubernetes.io/managed-by: Helm
    type: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
---
# Source: dragonfly/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
  namespace: go-scriptures
  labels:
    helm.sh/chart: dragonfly-v1.14.2
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/version: "v1.14.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: dragonfly
      protocol: TCP
      name: dragonfly
  selector:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
---
# Source: dragonfly/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly
  namespace: go-scriptures
  labels:
    helm.sh/chart: dragonfly-v1.14.2
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/version: "v1.14.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app.kubernetes.io/instance: dragonfly
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: dragonfly
        app.kubernetes.io/instance: dragonfly
    spec:
      serviceAccountName: dragonfly
      securityContext:
        fsGroup: 2000
      containers:
        - name: dragonfly
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.14.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: dragonfly
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - /usr/local/bin/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - /usr/local/bin/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          args:
            - "--alsologtostderr"
            - --cluster_mode=emulated
          resources:
            limits: {}
            requests: {}
          
          env:
            - name: DFLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cache-redis-cluster
                  key: redis-password
---
# Source: dragonfly/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dragonfly-metrics
  labels:
    helm.sh/chart: dragonfly-v1.14.2
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/version: "v1.14.2"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - interval: 10s
      scrapeTimeout: 10s
      honorLabels: true
      port: metrics
      path: /metrics
      scheme: http
  jobLabel: "dragonfly"
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app.kubernetes.io/instance: dragonfly
      type: metrics
  namespaceSelector:
    matchNames:
      - go-scriptures
```

The error stack is the same as the original post.  Let me debug a few things on this end.
