### ISSUE TITLE
Request a fixed nodeport

### ISSUE THREAD

**Issue by mueller-ma** [dragonflydb/dragonfly#3205]
**Did you search GitHub Issues and GitHub Discussions First?**

Yes

**Is your feature request related to a problem? Please describe.**

I'd like to run a Dragonfly cluster in Kubernetes and publish it to services running outside Kubernetes. For this I changed the service to type `NodePort`. Now a random port is assinged to this service.

```yaml
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-sample
  namespace: dragonfly
spec:
  serviceSpec:
    type: NodePort
```

**Describe the solution you'd like**

Add a new property `spec.serviceSpec.nodePort` to define a fixed port.
