### ISSUE TITLE
memcache mode does not accept unix timestamp

### ISSUE THREAD

**Issue by IgorOhrimenko** [dragonflydb/dragonfly#3418]
**Describe the bug**
The memcache protocol support specifying the expiration time in unix timestamp format:
https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L139
The Dragonfly accepts unix timestamp as seconds of expiration.

**To Reproduce**
<details>
  <summary>Dockerfile</summary>

```Dockerfile
FROM php:7.4
RUN apt-get -qq update && apt-get -qq --yes install libmemcached-dev zlib1g-dev \
    && pecl channel-update pecl.php.net \
    && pecl install memcached \
    && docker-php-ext-enable memcached
```
</details>
<details>
  <summary>compose.yaml</summary>

```yaml
services:
  php:
    build:
      context: .
    tty: true
    volumes:
      - ./test.php:/test.php
  memcached:
    image: memcached:latest
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.20.1
    ulimits:
      memlock: -1
    command: [
      "--max_log_size=20",
      "--memcached_port=11211",
      "--maxmemory=1gb",
      "--cache_mode=true",
      "--alsologtostderr=true",
      "--dbnum=1",
      "--proactor_threads=1"
    ]
```
</details>
<details>
  <summary>test.php</summary>

```php
<?php

$memcached = new Memcached();
$memcached->addServers([['host' => 'memcached','port' => '11211',]]);

$dragonfly = new Memcached();
$dragonfly->addServers([['host' => 'dragonfly','port' => '11211',]]);

echo "memcached set " . time() . " +10s\n";
$memcached->set('key', time() + 10, time() + 10);

echo "dragonfly set " . time() . " +10s\n";
$dragonfly->set('key', time() + 10, time() + 10);

sleep(9);
echo "\nAfter 9 seconds\n";
echo 'memcached ' . $memcached->get('key') . "\n";
echo 'dragonfly ' . $dragonfly->get('key') . "\n";

sleep(2);
echo "\nAfter 11 seconds\n";
echo 'memcached ' . $memcached->get('key') . "\n";
echo 'dragonfly ' . $dragonfly->get('key') . "\n";
```
</details>

```bash
docker compose up --detach --build
docker compose exec php php test.php
```

**Expected behavior**
The key expires after the unix timestamp.

**Additional context**
```
memcached set 1722444217 +10s
dragonfly set 1722444217 +10s

After 9 seconds
memcached 1722444227
dragonfly 1722444227

After 11 seconds
memcached
dragonfly 1722444227
```
