### ISSUE TITLE
Deploying with Rails 8 with kamal 2

### ISSUE THREAD

**Issue by sandip-mane** [dragonflydb/dragonfly#4089]
**Describe the bug**
I am unable to deploy it with Rails 8 using Kamal 2.

<details>
<summary><b>Here's the config I am using:</b></summary>

```yaml
service: rails_8_with_dragonflydb
image: xxx/rails_8_with_dragonflydb
servers:
  web:
    - xxx.xx.xxx.xxx

registry:
  username: xxxx
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    REDIS_URL: "redis://rails_8_with_dragonflydb-dragonflydb:6379/0"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "rails_8_with_dragonflydb_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    cmd: "docker.dragonflydb.io/dragonflydb/dragonfly --network=host --ulimit memlock=-1"
    roles:
      - web
    directories:
      - dragonflydata:/data
```
</details>

<details>
<summary><b>Redis config that works fine:</b></summary>

```yaml
service: rails_8_with_redis
image: xxxx/rails_8_with_redis
servers:
  web:
    - xxx.xx.xxx.xx

registry:
  username: xxxx
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    REDIS_URL: "redis://rails_8_with_redis-redis:6379/0"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "rails_8_with_redis_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  redis:
    image: redis:7.2.3
    roles:
      - web
    directories:
      - data:/data
```
</details>

**To Reproduce**
After deploying, 
1. Run `kamal console`
2. Run `Redis.new.keys("*")`

**Screenshots**
![CleanShot 2024-11-08 at 18 56 31](https://github.com/user-attachments/assets/a4a52ebd-1334-4b3b-97d3-190586a61589)

**Environment (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Kernel: # Command: `uname -a`
 - Containerized?: Bare Metal, Docker
 - Dragonfly Version: docker.dragonflydb.io/dragonflydb/dragonfly docker image
