### ISSUE TITLE
dragonflydb immich

### ISSUE THREAD

**Issue by rafalohaki** [dragonflydb/dragonfly#4249]
when i change redis to dragonflydb in immich

```
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
```
 to
    
```
  redis:
    container_name: immich_redis
    image: ghcr.io/dragonflydb/dragonfly:latest
    restart: always
```

there is a problem with uploading

```
[Nest] 18  - 12/03/2024, 11:36:44 PM   ERROR [Api:ErrorInterceptor~u9e21qdd] Unknown error: ReplyError: ERR Error running script (call to b13c1227791fc1cac2ed45d06765e4dc2618b9cb): @user_script:70: script tried accessing undeclared key, key: immich_bull:backgroundTask:1
ReplyError: ERR Error running script (call to b13c1227791fc1cac2ed45d06765e4dc2618b9cb): @user_script:70: script tried accessing undeclared key, key: immich_bull:backgroundTask:1
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```
