### ISSUE TITLE
Potential bug in entrypoint script

### ISSUE THREAD

**Issue by applike-ss** [dragonflydb/dragonfly#4251]
**Describe the bug**
When i start my dragonfly test container via the following command the io threads are correctly set:
```
# set proactor threads to 1
docker run -it --rm ghcr.io/dragonflydb/dragonfly:v1.25.4-ubuntu --proactor_threads=1
# > I20241204 09:13:18.126736     1 proactor_pool.cc:147] Running 1 io threads

# set proactor threads to 2
docker run -it --rm ghcr.io/dragonflydb/dragonfly:v1.25.4-ubuntu --proactor_threads=2
# > I20241204 09:07:52.068485     1 proactor_pool.cc:147] Running 2 io threads
```

When i now try to achieve the same in my k3d test kubernetes cluster, it does always set the proactor threads to the amount of threads available to the pod. This would be fine if i currently did have another issue where limiting the pod resources isn't working correctly.

snippet from the pod:
```
  containers:
    - name: dragonfly
      image: ghcr.io/dragonflydb/dragonfly:v1.25.4
      args:
        - '--proactor_threads=1'
```

**To Reproduce**
1. `k3d cluster create`
2. Install dragonfly operator as per documentation `kubectl apply -f https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/main/manifests/dragonfly-operator.yaml`
3. Create dragonfly cluster via Dragonfly resource with args passed
4. See log message showing a different amount of proactor threads

Demo Resource:
```yaml
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly-sample
  namespace: default
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.25.4
  args:
    - '--maxmemory=512M'
    - '--proactor_threads=1'
  replicas: 2
  resources:
    limits:
      cpu: 2
      memory: 768Mi
    requests:
      cpu: 2
      ephemeral-storage: 1Gi
      memory: 768Mi
```

**Expected behavior**
Setting proactor threads (potentially other flags are also affected?) should work the same, no matter whether using docker or k8s/containerd

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: Darwin + Linux
 - Kernel: 6.10.14-linuxkit
 - Containerized?: Docker and Kubernetes
 - Dragonfly Version: 1.25.4

**Reproducible Code Snippet**
see above at "To reproduce"

**Additional context**
-
