### ISSUE TITLE
Prometheus metrics broken on prom 3.0

### ISSUE THREAD

**Issue by ishioni** [dragonflydb/dragonfly#4277]
**Describe the bug**
Prometheus 3.0 rejects the scrape because dragonfly does not set content-type

**To Reproduce**
1. curl http://dragonflydb:adminport
2. note the lack of content-type in the http response header
3. Prometheus 3.0 complains with "Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target"

**Expected behavior**
Prometheus metrics should work

**Screenshots**

**Environment (please complete the following information):**
 - OS: [talos 1.8]
 - Kernel: # 6.6
 - Containerized?: [Kubernetes]
 - Dragonfly Version: [1.25.4]

**Additional context**
Setting something like 
content-type text/plain; version=0.0.4; charset=utf-8; escaping=underscores 
should be enough to make it work. Adding a fallback_scrape_protocol should be good as well, but the prometheus operator CRDs don't allow that unfortunately

More context https://prometheus.io/docs/prometheus/3.0/migration/#scrape-protocols

**Comment by romange** [comment]
@ishioni should be easy to fix. would you like to take a stab on it?

**Comment by ishioni** [comment]
Wish I could - last time I touched cpp was over a decade ago in college

**Comment by lnd-d** [comment]
I added this to prometheus.yml meanwhile.

```
global:
 metric_name_validation_scheme: legacy
```

**Comment by beauwest** [comment]
A more targeted solution for now is to apply a `fallBackScrapeProtocol` to the ServiceMonitor or PodMonitor.

Full example:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dragonfly-servicemonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
  endpoints:
    - port: service-port
  fallbackScrapeProtocol: PrometheusText1.0.0
```
