### ISSUE TITLE
Keys lost during direct Redis-to-Dragonfly migration

### ISSUE THREAD

**Issue by nikatar** [dragonflydb/dragonfly#4292]
**Describe the bug**  
I need to transfer all keys and their values directly from Redis to Dragonfly without using replication or RDB backups. I tried two methods that employ similar approaches to key scanning and data transfer:

1. Using RedisShake with the configuration below.  
2. Using a custom script that relies on the `SCAN` and `MIGRATE` commands.

Both RedisShake and the custom script were run from a separate Alpine:3.20 pod in the same namespace as Redis and Dragonfly. In both scenarios, the result was the same: only a small portion of keys appear on the Dragonfly instance compared to the original amount in Redis (see screenshot).

However, when I tried migrating keys from Redis to another Redis instance using the same methods (RedisShake and the custom script), the process worked correctly and all keys were transferred.

**To Reproduce**  
1. Have a Redis instance with a large number of keys (~219k).  
2. Use either RedisShake with the provided configuration or custom script(`SCAN` + `MIGRATE`) to transfer keys directly to Dragonfly.  
3. After completion, checking the key count in Dragonfly reveals significantly fewer keys than on the source Redis.

**Expected behavior**  
All keys from Redis should be successfully transferred to Dragonfly, preserving their count and values.

**Screenshots**  
A screenshot shows the source Redis with ~219,701 keys and the target Dragonfly with only ~8,256 keys after the migration.
![изображение](https://github.com/user-attachments/assets/bc1f83a1-88dd-4e41-af00-4d8fb0aaa918)

**Environment:**  
- OS: Amazon Linux 2  
- Containerized?: Kubernetes (EKS)  
- Dragonfly Operator: v1.1.8  
- Dragonfly Version: v1.25.4  
- Dragonfly Configuration:
  ```yaml
  spec:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.25.4
    replicas: 1
    resources:
      requests:
        cpu: 600m
        memory: 4Gi
      limits:
        memory: 6Gi
    args: ["--dbfilename=backup"]
    snapshot:
      cron: "*/5 * * * *"
      persistentVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    nodeSelector:
      eks.amazonaws.com/capacityType: ON_DEMAND
      infra: "true"
    tolerations:
      - key: "infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "karpenter"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  ```

- Redis Chart: bitnami/redis version: 19.5.0, appVersion: 7.2.5  
  Values:
  ```yaml
  nameOverride: redis-click-0
  fullnameOverride: redis-click-0
  architecture: standalone
  replica:
    kind: StatefulSet
    replicaCount: 0
  auth:
    enabled: false
  master:
    extraFlags:
      - "--maxmemory 1024M"
    resources:
      limits:
        cpu: 1000m
        memory: 1296Mi
    nodeSelector:
      eks.amazonaws.com/capacityType: ON_DEMAND
      infra: "true"
    tolerations:
      - key: "infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "karpenter"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.59.0-debian-12-r6
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
  ```

**RedisShake configuration:**
```toml
[scan_reader]
cluster = false
address = "redis-click-0-master.redis.svc.cluster.local:6379"
username = ""
password = ""
tls = false
dbs = []
scan = true
ksn = false
count = 500

[redis_writer]
cluster = false
sentinel = false
address = "dragonfly-clicker.redis.svc.cluster.local.redis.svc.cluster.local:6379"
username = ""
password = ""
tls = false
off_reply = false
```

**Reproducible Code Snippet (SCAN + MIGRATE):**  
```bash
#!/usr/bin/env bash

set -e

source_host="redis-click-0-master.redis.svc.cluster.local"
source_port=6379
source_db=0

target_host="dragonfly-clicker.redis.svc.cluster.local"
target_port=6379
target_db=0

timeout=5000
batch_size=100

cursor=0
keys=()

while true; do
    result=$(redis-cli -h $source_host -p $source_port -n $source_db SCAN $cursor COUNT $batch_size)
    new_cursor=$(echo "$result" | head -n 1)
    scanned_keys=$(echo "$result" | tail -n +2)

    for k in $scanned_keys; do
        keys+=("$k")
        if [ "${#keys[@]}" -ge $batch_size ]; then
            redis-cli -h $source_host -p $source_port -n $source_db MIGRATE $target_host $target_port "" $target_db $timeout COPY KEYS "${keys[@]}"
            keys=()
        fi
    done

    if [ "$new_cursor" = "0" ]; then
        if [ "${#keys[@]}" -gt 0 ]; then
            redis-cli -h $source_host -p $source_port -n $source_db MIGRATE $target_host $target_port "" $target_db $timeout COPY KEYS "${keys[@]}"
        fi
        break
    fi

    cursor=$new_cursor
done
```

**Additional Info**  
Also, here is a link to the RedisShake documentation: [RedisShake scan_reader](https://tair-opensource.github.io/RedisShake/en/reader/scan_reader.html#full-data)
