### ISSUE TITLE
provide testing coverage using mastodon tests

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#4596]
The mastodon project runs extensive tests involving redis.

We can extract their [test.](https://github.com/mastodon/mastodon/blob/main/.github/workflows/test-ruby.yml) 
with say, [test (.ruby version)](https://github.com/mastodon/mastodon/actions/runs/13283342329/job/37086513361) into our repo and run it periodically. Similarly to what we do with bullmq. `test (.ruby version)` is the latest stable version (3.4)

**Comment by abhijat** [comment]
The good thing is that both running locally against dragonfly as well as in gh actions the test suite reports only two failures out of 6020 tests run, will look into these

```
Finished in 27.1 seconds (files took 5.57 seconds to load)
6020 examples, 2 failures

Failed examples:

rspec ./spec/workers/scheduler/self_destruct_scheduler_spec.rb:42 # Scheduler::SelfDestructScheduler#perform when in self-destruct mode when sidekiq is operational suspends local non-suspended accounts
rspec ./spec/workers/scheduler/self_destruct_scheduler_spec.rb:48 # Scheduler::SelfDestructScheduler#perform when in self-destruct mode when sidekiq is operational suspends local suspended accounts marked for deletion
```

These same also failed in a github actions workflow where we ultimately will run this https://github.com/dragonflydb/dragonfly/actions/workflows/mastodon-ruby-tests.yml

```
Failures:

  1) Scheduler::SelfDestructScheduler#perform when in self-destruct mode when sidekiq is operational suspends local non-suspended accounts
     Failure/Error: expect(account.reload.suspended_at).to_not be_nil

       expected: not nil
            got: nil
     # ./spec/workers/scheduler/self_destruct_scheduler_spec.rb:45:in 'block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:140:in 'block (2 levels) in <top (required)>'

  2) Scheduler::SelfDestructScheduler#perform when in self-destruct mode when sidekiq is operational suspends local suspended accounts marked for deletion
     Failure/Error: expect(account.reload.suspended_at).to be > 1.day.ago

       expected: > 2025-04-15 09:40:49.644524521 +0000
            got:   2025-04-06 09:40:49.612351000 +0000
     # ./spec/workers/scheduler/self_destruct_scheduler_spec.rb:54:in 'block (5 levels) in <top (required)>'
     # ./spec/rails_helper.rb:140:in 'block (2 levels) in <top (required)>'
```
