### ISSUE TITLE
Bug: Built-in update check returns `unknown version`, when blocked by firewall

### ISSUE THREAD

**Issue by tamcore** [dragonflydb/dragonfly#603]
I just had noticed, that there's a built-in update-check, which prints a message during startup.

When I deny Dragonfly all Egress via
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
```
it just prints
> 09:45:45.791925    13 dfly_main.cc:204] Your current version '77ef095' is not the latest version. A newer version 'unknown version' is now available. Please consider an update.

Which I believe is a bug. It should be able to catch the network error and report accordingly, that it wasn't able to check for updates.

Additionally, there should be a flag to disable the check as well as documentation, that Dragonfly will make outbound connections towards `https://version.dragonflydb.io/v1`.
