### ISSUE TITLE
[QUESTION] Why Dragonfly is slower than redis on golang stack?

### ISSUE THREAD

**Issue by akuzia** [dragonflydb/dragonfly#81]
Considering dragonfly as drop in replacment for redis on high throughput/low latency caching.
Below is a simple "benchmark" to compare db read/write performance. It Writes sample db with 100k keys, then read them, simulating 10 concurrent clients. So ~100mb of concurrent data traffic in and out.

Results
```
dragonfly-vs-redis-bench-1  | Redis:
dragonfly-vs-redis-bench-1  | Populating db took 1.775606069s
dragonfly-vs-redis-bench-1  | Reading db took 1.6870264s
dragonfly-vs-redis-bench-1  | ====================
dragonfly-vs-redis-bench-1  | Dragonfly:
dragonfly-vs-redis-bench-1  | Populating db took 12.969991441s
dragonfly-vs-redis-bench-1  | Reading db took 12.966059586s
```

Reproduce:

compose
```yml
version: '3'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly

  redis:
    image: redis:7

  bench:
    image: golang:1.18
    working_dir: /var/app
    command: ['go', 'run', 'main.go']
    volumes:
      - .:/var/app

```
main.go
```golang
package main

import (
	"encoding/base64"
	"fmt"
	"math/rand"
	"sync"
	"time"

	"github.com/go-redis/redis"
)

func main() {
	fmt.Println("Redis:")
	redisCLient := redis.NewClient(&redis.Options{
		Addr:     "redis:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(redisCLient)
	fmt.Println("====================")

	fmt.Println("Dragonfly:")
	dragonflyClient := redis.NewClient(&redis.Options{
		Addr:     "dragonfly:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(dragonflyClient)
}

func benchRedisClient(client *redis.Client) {
	startPopulating := time.Now()

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		go func(i int) {
			for j := 0; j < 10000; j++ {
				token := make([]byte, 1000)
				rand.Read(token)

				val := base64.StdEncoding.EncodeToString(token)
				key := fmt.Sprintf("key%d", i*10000+j)

				client.Set(key, val, 0)
			}
			wg.Done()
		}(i)
		wg.Add(1)
	}
	wg.Wait()
	fmt.Printf("Populating db took %s\n", time.Since(startPopulating))

	startReading := time.Now()
	for i := 0; i < 10; i++ {
		minKey := i * 10000
		maxKey := (i + 1) * 10000

		go func() {
			for i := minKey; i < maxKey; i++ {
				client.Get(fmt.Sprintf("key%d", i))
			}
			wg.Done()
		}()
		wg.Add(1)
	}

	wg.Wait()
	fmt.Printf("Reading db took %s\n", time.Since(startReading))
}
```

Why dragonfly is almost 10 times slower with the same usage scenario? And performance scales almost linearly with number of goroutines:
5 = ~5sec r/w
20 = ~20sec r/w
etc.
