### ISSUE TITLE
k8s helm set password ,connect error.

### ISSUE THREAD

**Issue by dahvlhldle** [dragonflydb/dragonfly#839]
In helm value.yaml
```
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dfly-password
    stringData:
      password: foobar

passwordFromSecret:
  enable: true
  existingSecret:
    name: dfly-password
    key: password
```
 k8s  pod is stated success ,but when i connect to db,i get error 
`ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct`
