### ISSUE TITLE
Add 'namespace' attribute into Dragonfly helm chart

### ISSUE THREAD

**Issue by RacekM** [dragonflydb/dragonfly#874]
# Problem description
Most of the manifests in Dragonfly helm chart do not have a namespace attribute. The only one is ServiceMonitor and PrometheusRule.

Would it be possible to add it to other templates? 

If I run the following command then the rendered yaml does not work as it should cause all information about the namespace is lost. 
`helm template cache -n cache .` 

# Actual behavior
**Executed command:**
`helm template cache -n cache .`

**Output:**
```
---
# Source: dragonfly/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-dragonfly
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: dragonfly/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cache-dragonfly
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: dragonfly
      protocol: TCP
      name: dragonfly
  selector:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
---
# Source: dragonfly/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dragonfly
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app.kubernetes.io/instance: cache
  template:
...
```

# Expected behaviour
**Executed command:**
`helm template cache -n cache .`

**Output:**
```
---
# Source: dragonfly/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-dragonfly
  namespace: cache
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: dragonfly/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cache-dragonfly
  namespace: cache
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: dragonfly
      protocol: TCP
      name: dragonfly
  selector:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
---
# Source: dragonfly/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dragonfly
  namespace: cache
  labels:
    helm.sh/chart: dragonfly-v0.15.0
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: cache
    app.kubernetes.io/version: "v0.15.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app.kubernetes.io/instance: cache
  template:
...
```

# Suggested solution
All what is needed to be done is to add `name: {{ .Release.name }}` into separate manifest files.
