### ISSUE TITLE
Unable to use helm chart as dependency

### ISSUE THREAD

**Issue by Scarjit** [dragonflydb/dragonfly#995]
**Describe the bug**
When attempting to use dragonfly as a dependency in a helm chart, execuing `helm dependency update` errors with 403

**To Reproduce**
1. Create a sample Chart.yaml file (note that i have tested it with 1.0.0 and v1.0.0):
```
appVersion: 1.0.5
apiVersion: v2
name: my-chart
description: A Helm chart for deploying my-chart
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.5
- name: dragonfly
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
  version: 1.0.0
version: 0.43.5
```
4. Execute `helm dependency update`
6. See error
```
PS D:\project> helm dependency update           
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "united-manufacturing-hub" chart repository
...Successfully got an update from the "minio" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Downloading dragonfly from repo oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
Save error occurred:  could not download oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly/dragonfly: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
Error: could not download oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly/dragonfly: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

**Expected behavior**
It should download the chart

**Screenshots**
![screenshot](https://i.soontm.net/Yipu5/desEsame92.png/raw)

**Environment (please complete the following information):**
 - OS: Windows 11 22621.1413
 - Helm Version: version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"} [As time of writing this is the latest Helm version]

**Reproducible Code Snippet**
```
appVersion: 1.0.5
apiVersion: v2
name: my-chart
description: A Helm chart
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.5
- name: dragonfly
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
  version: 1.0.0
version: 0.43.5
```
Note: I included postgresql, showing that the download itself works
